table Dim_Product
	lineageTag: 96e0a317-1d11-4357-a6ca-abf52b8ade76

	column Product
		dataType: string
		lineageTag: dc4ab545-6732-4bca-a37b-48e0757a8202
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 1b4d1fd9-f7fe-443b-a4fe-787de85c40ed
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	partition Dim_Product = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\danish.mohammed\Documents\samsung_supply_chain_fact_table.xlsx"), null, true),
				    Dim_Product_Sheet = Source{[Item="Dim_Product",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Dim_Product_Sheet,{{"Column1", type text}, {"Column2", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Product", type text}, {"Category", type text}}),
				    #"Demoted Headers" = Table.DemoteHeaders(#"Changed Type1"),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Demoted Headers",{{"Column1", type text}, {"Column2", type text}}),
				    #"Promoted Headers1" = Table.PromoteHeaders(#"Changed Type2", [PromoteAllScalars=true]),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Promoted Headers1",{{"Product", type text}, {"Category", type text}}),
				    #"Demoted Headers1" = Table.DemoteHeaders(#"Changed Type3"),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Demoted Headers1",{{"Column1", type text}, {"Column2", type text}}),
				    #"Promoted Headers2" = Table.PromoteHeaders(#"Changed Type4", [PromoteAllScalars=true]),
				    #"Changed Type5" = Table.TransformColumnTypes(#"Promoted Headers2",{{"Product", type text}, {"Category", type text}})
				in
				    #"Changed Type5"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

